services:
  db:
    image: postgis/postgis:15-3.3
    container_name: noc_postgres_db
    restart: always
    environment:
      POSTGRES_USER: noc_admin
      POSTGRES_PASSWORD: noc_secure_password_123
      POSTGRES_DB: noc_platform_db
    ports:
      # Format is HOST_PORT:CONTAINER_PORT
      # We use 5433 locally to avoid conflict with your native Postgres
      - "5433:5432"
    volumes:
      - noc_pg_data:/var/lib/postgresql/data
      - ./db/init-scripts:/docker-entrypoint-initdb.d

volumes:
  noc_pg_data: