"""Create unified ServiceOrder table

Revision ID: 23d4a4ad5d49
Revises: 
Create Date: 2026-04-05 10:40:18.068647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23d4a4ad5d49'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_orders',
    sa.Column('order_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('service_category', sa.Enum('FTTH', 'DIA', 'DARK_FIBER', 'LAYER_2', name='servicecategory'), nullable=False),
    sa.Column('customer_name', sa.String(), nullable=False),
    sa.Column('service_address', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('isp', sa.Enum('MTNN', 'METROREACH', 'MANGONET', name='isptype'), nullable=False),
    sa.Column('bandwidth', sa.String(), nullable=False),
    sa.Column('fn_number', sa.String(), nullable=True),
    sa.Column('service_order_number', sa.String(), nullable=True),
    sa.Column('service_id', sa.String(), nullable=True),
    sa.Column('pfp_id', sa.UUID(), nullable=True),
    sa.Column('pfs_id', sa.UUID(), nullable=True),
    sa.Column('pfs_port', sa.Integer(), nullable=True),
    sa.Column('nap_id', sa.UUID(), nullable=True),
    sa.Column('nap_port', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('REQUESTED', 'PFS_TESTING', 'NAP_TESTING', 'ROSETTE_TESTING', 'DROP_INSTALLATION', 'ACTIVE', 'CANCELLED', name='workflowstage'), nullable=True),
    sa.Column('pfs_power_level', sa.String(), nullable=True),
    sa.Column('nap_power_level', sa.String(), nullable=True),
    sa.Column('rosette_power_level', sa.String(), nullable=True),
    sa.Column('tester_type', sa.String(), nullable=True),
    sa.Column('drop_tech_name', sa.String(), nullable=True),
    sa.Column('cpe_tech_name', sa.String(), nullable=True),
    sa.Column('noc_personnel_id', sa.UUID(), nullable=True),
    sa.Column('requested_by_id', sa.UUID(), nullable=True),
    sa.Column('approved_by_id', sa.UUID(), nullable=True),
    sa.Column('planned_install_date', sa.DateTime(), nullable=True),
    sa.Column('completion_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('order_id'),
    sa.UniqueConstraint('service_id'),
    sa.UniqueConstraint('service_order_number')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('service_orders')
    
    # Explicitly drop enums to avoid clutter if downgraded
    sa.Enum(name='workflowstage').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='isptype').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='servicecategory').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###