"""add_allocation_columns_to_service_order

Revision ID: ffc980c60b1b
Revises: ab7c59588a2e
Create Date: 2026-04-05 16:02:50.263818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ffc980c60b1b'
down_revision: Union[str, Sequence[str], None] = 'ab7c59588a2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # We stripped out all the autogenerated TEXT -> String noise.
    # This guarantees it won't break database Views in production!
    op.add_column('service_orders', sa.Column('drop_cable_id', sa.UUID(), nullable=True))


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_column('service_orders', 'drop_cable_id')